[package]
name = "aosa"
version = "0.1.0"
edition = "2021"
authors = ["jiangzhe <nju.jiangzhe@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Append-only string arena"
keywords = ["string", "arena"]
repository = "https://github.com/jiangzhe/aosa/"

[dependencies]
thiserror = "1.0"
